### ISSUE TITLE
Toelichten van de term 'radicaal open'

### ISSUE THREAD

**Issue by adbgnm** [Geonovum/DSGO#5]
Er is onduidelijke wat radicaal open betekent, ook in relatie tot gewoon open.

Is dat 'open tenzij, ...'?

**Comment by PalmJanssen** [comment]
in het vocabulaire van het radicalisme komen de condities 'tenzij' en 'mits' niet voor.

**Comment by JanBruijn** [comment]
Ik heb radicaal weggelaten in dit verband.
essentie is dat de openheid van oorsprong van data achterhaald kan worden. Dat bewerkingen niet verscholen zitten binnen een platform van een leverancier dat niet transparant toegankelijk is.
